name: Cypress E2E Tests
on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Which tests you wants to run"
        default: "@smoke"
        required: true
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: E2E
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Cypress test
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headed: false
          env: grepTags=${{ inputs.tags }}

      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cypress-allure-results
          path: allure-results
          if-no-files-found: ignore

    #   - name: Generate allure report
    #     uses: simple-elf/allure-report-action@master
    #     if: always()
    #     id: allure-report
    #     with:
    #       allure_results: allure-results
    #       gh_pages: gh-pages
    #       allure_report: allure-report
    #       allure_history: allure-history

    #   - name: Deploy report to Branch
    #     if: always()
    #     uses: peaceiris/actions-gh-pages@v2
    #     env:
    #       PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #       PUBLISH_BRANCH: gh-pages
    #       PUBLISH_DIR: allure-history
